# Generated by Django 2.0.3 on 2018-03-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180315_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('airline', models.OneToOneField(db_column='Airline_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Flight_Airline', serialize=False, to='polls.Airline')),
                ('flight_id', models.IntegerField(db_column='Flight_ID')),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('fare', models.IntegerField(blank=True, db_column='Fare', null=True)),
                ('workday', models.IntegerField(blank=True, db_column='Workday', null=True)),
                ('depart_time', models.TimeField(blank=True, db_column='Depart_time', null=True)),
                ('arrive_time', models.TimeField(blank=True, db_column='Arrive_time', null=True)),
                ('arrive_airport', models.ForeignKey(blank=True, db_column='Arrive_Airport', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Flight_Arrive_Airport', to='polls.Airport')),
                ('depart_airport', models.ForeignKey(blank=True, db_column='Depart_Airport', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Flight_Depart_Airport', to='polls.Airport')),
                ('fare_0', models.ForeignKey(blank=True, db_column='Fare_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.FareRestriction')),
            ],
            options={
                'db_table': 'Flights',
            },
        ),
        migrations.AlterUniqueTogether(
            name='flights',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='flights',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='arrive_airport',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='depart_airport',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='fare_0',
        ),
        migrations.AddField(
            model_name='account',
            name='airline',
            field=models.ForeignKey(blank=True, db_column='Airline_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account_Airline', to='polls.ReservationInfo'),
        ),
        migrations.AddField(
            model_name='account',
            name='flight',
            field=models.ForeignKey(blank=True, db_column='Flight_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account_flight', to='polls.ReservationInfo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_card',
            field=models.CharField(blank=True, db_column='Credit_card', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='delay',
            name='airline',
            field=models.ForeignKey(db_column='Airline_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Delay_Airline', serialize=False, to='polls.Flight'),
        ),
        migrations.AlterField(
            model_name='delay',
            name='flight',
            field=models.ForeignKey(db_column='Flight_ID', on_delete=django.db.models.deletion.CASCADE, related_name='Delay_Flight', to='polls.Flight'),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='airline',
            field=models.ForeignKey(db_column='Airline_ID', on_delete=django.db.models.deletion.CASCADE, related_name='Reserve_Airline', to='polls.Flight'),
        ),
        migrations.AlterField(
            model_name='reservationinfo',
            name='flight',
            field=models.ForeignKey(db_column='Flight_ID', on_delete=django.db.models.deletion.CASCADE, related_name='Reserve_Flight', to='polls.Flight'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('customer', 'account_id', 'reservation', 'airline', 'flight')},
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.AlterUniqueTogether(
            name='reservationinfo',
            unique_together={('reservation_id', 'airline', 'flight')},
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('airline', 'flight_id')},
        ),
    ]
