# Generated by Django 2.0.3 on 2018-03-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180316_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='Flights',
        ),
    ]
