# Generated by Django 2.0.3 on 2018-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180316_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
